module Constants
  SPECIALTIES = {
    acupuncturist: "Acupuncturist",
    allergist: "Allergist",
    anesthesiologist: "Anesthesiologist",
    cardiologist: "Cardiologist",
    cardiothoracic: "Cardiothoracic Surgeon",
    dermatologist: "Dermatologist",
    embryologist: "Embryologist",
    er_physician: "Emergency Room Physician",
    endocrinologist: "Endocrinologist",
    family: "Family Medicine or Family Practicioner",
    gastroeterologist: "Gastroenterologist",
    gp: "General Practicioner",
    geneticist: "Geneticist",
    geriatrician: "Geriatrician",
    gynecologist: "Gynecologist",
    hematologist: "Hematologist",
    hospitalist: "Hospitalist",
    immunologist: "Immunologist",
    internist: "Internist",
    invasive_cardio: "Invasive Cardiologist",
    naturopathi: "Naturopathic Physician",
    neonatologist: "Neonatologist",
    nephrologist: "Nephrologist",
    neurologist: "Neurologist",
    neurootologist: "Neuro-Otologist",
    nuclear: "Nuclear Medicine",
    obsterician: "Obsterician",
    occupational: "Occupational Medicine",
    oncologist: "Oncologist",
    opthalmologist: "Opthalmologist",
    orthopedist: "Orthopedist",
    osteopath: "Osteopath",
    otolaryngologist: "Otolarynologist Ear - Nose - Throat",
    otologist: "Otologist",
    pain: "Pain Management",
    pathologist: "Pathologist",
    pediatrician: "Pediatrician",
    perfusionist: "Perfusionist",
    physiatrist: "Physiatrist/Physical Medicine/Rehabilitation",
    plastic: "Plastic Surgeon",
    proctologist: "Proctologist",
    psychiatrist: "Psychiatrist",
    pulmonologist: "Pulmonologist",
    radiologist: "Radiologist",
    rheumatologist: "Rheumatologist",
    surgeon: "Surgeon",
    thoracic: "Thoracic Surgeon",
    urologist: "Urologist"
  }
end